[terminal]
vt = 1

[default_session]
# command = "tuigreet -r --remember-session --user-menu --theme \"border=magenta;text=cyan;prompt=green;time=red;action=blue;button=yellow;container=black;input=red\" -c Hyprland"
command = "tuigreet -r --remember-session --user-menu -t -c start-hyprland"
user = "neo"
