import = [
  "~/.config/alacritty/themes/tokyo-night.toml"
]

live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
unfocused_hollow = true
# blink_interval = 500
# blink_timeout = 5

[font.normal]
family = "FiraMono Nerd Font"
style = "Regular"

[font.italic]
family = "FiraMono Nerd Font"
style = "Italic"

[font.bold]
family = "FiraMono Nerd Font"
style = "Bold"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[window]
decorations = "full"
dynamic_title = true
option_as_alt = "Both"
opacity = 0.85

[window.padding]
x = 8
y = 8
